version: '3.1'

services:
    
    web-server:
        image: webdev89/debianredis
        restart: always
        container_name: php-redis 
        ports:
          - 8930:80
        environment:
            DB_HOST: db
            DB_DB: redis
            DB_USER: user
            DB_PASS: user
            REDIS: redis
        volumes:
          - ./dist/:/var/www/html
        depends_on:
          - db
        networks:
          - redis
          
    redis:
        image: redis
        container_name: redis
        restart: always
        networks:
          - redis
          
    db:
        image: mysql:5.7
        container_name: MysqlRedis
        restart: always
        ports:
          - 8936:3306
        environment:
          MYSQL_DATABASE: redis
          MYSQL_USER: user 
          MYSQL_PASSWORD: user
          MYSQL_ROOT_PASSWORD: root
        volumes:
          - ./mysql_dump:/docker-entrypoint-initdb.d
          - Mysqlredis:/var/lib/mysql
        networks:
          - redis

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin_redis
        restart: always
        ports: 
          - 8937:80
        environment:
          PMA_HOST: db
        depends_on:
          - db
        networks:
          - redis
          
networks:
  redis:
    driver: bridge

volumes:
  Mysqlredis: